# Generated by Django 5.2.17 on 2026-08-30 03:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('device_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('platform', models.CharField(choices=[('WEB', 'Web / Navegador'), ('ANDROID_PWA', 'PWA Android'), ('IOS_PWA', 'PWA iOS'), ('UNKNOWN', 'Desconocido')], default='WEB', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='academics.guardian')),
            ],
            options={
                'verbose_name': 'Dispositivo de Tutor',
                'verbose_name_plural': 'Dispositivos de Tutor',
                'db_table': 'guardian_devices',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianActivationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=5)),
                ('attempt_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_activation_codes', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='academics.guardian')),
            ],
            options={
                'verbose_name': 'Código de Activación de Tutor',
                'verbose_name_plural': 'Códigos de Activación de Tutor',
                'db_table': 'guardian_activation_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guardian', 'expires_at'], name='guardian_ac_guardia_578867_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='FCM', max_length=20)),
                ('token_encrypted_or_protected', models.TextField()),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='guardians.guardiandevice')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'token_hash')},
            },
        ),
    ]
