# Generated by Django 5.2.17 on 2026-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiandevice',
            name='platform',
            field=models.CharField(choices=[('WEB', 'Web / Navegador'), ('ANDROID_PWA', 'PWA Android'), ('IOS_PWA', 'PWA iOS'), ('ANDROID_APP', 'App Nativa Android (APK)'), ('IOS_APP', 'App Nativa iOS (Apple)'), ('UNKNOWN', 'Desconocido')], default='WEB', max_length=20),
        ),
    ]
