# Generated by Django 5.2.17 on 2026-09-04 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicperiod'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='academics.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='academics.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='academics.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='academics.teacher')),
            ],
            options={
                'verbose_name': 'Libro de Calificaciones',
                'verbose_name_plural': 'Libros de Calificaciones',
                'db_table': 'gradebooks',
                'ordering': ['academic_year', 'academic_period__number', 'course', 'subject'],
                'unique_together': {('academic_year', 'academic_period', 'course', 'subject', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='GradeActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('activity_type', models.CharField(choices=[('TASK', 'Tarea'), ('EXAM', 'Examen'), ('PRACTICE', 'Práctica'), ('PROJECT', 'Proyecto'), ('PRESENTATION', 'Exposición'), ('PARTICIPATION', 'Participación'), ('OTHER', 'Otro')], default='TASK', max_length=30)),
                ('activity_date', models.DateField()),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='grades.gradebook')),
            ],
            options={
                'verbose_name': 'Actividad Calificada',
                'verbose_name_plural': 'Actividades Calificadas',
                'db_table': 'grade_activities',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='grades.gradeactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_entries_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='academics.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_entries_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Calificación',
                'verbose_name_plural': 'Registros de Calificaciones',
                'db_table': 'grade_entries',
                'indexes': [models.Index(fields=['activity', 'student'], name='grade_entri_activit_e8e341_idx')],
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
