# Generated by Django 5.2.17 on 2026-08-30 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('alerts', '0001_initial'),
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ACADEMIC_ALERT', 'Alerta Académica'), ('ATTENDANCE_ALERT', 'Alerta de Asistencia'), ('GENERAL', 'Comunicado General')], default='ACADEMIC_ALERT', max_length=30)),
                ('safe_title', models.CharField(default='Colegio Gabriel René Moreno II', max_length=200)),
                ('safe_body', models.TextField(default='Tiene una nueva notificación académica.')),
                ('detailed_title', models.CharField(max_length=200)),
                ('detailed_body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alerts.alertevent')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academics.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='academics.student')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='FCM', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('INVALID_TOKEN', 'Token Inválido'), ('SKIPPED', 'Omitido')], default='PENDING', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message_redacted', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
                ('push_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='guardians.pushsubscription')),
            ],
            options={
                'verbose_name': 'Entrega de Notificación',
                'verbose_name_plural': 'Entregas de Notificación',
                'db_table': 'notification_deliveries',
                'ordering': ['-last_attempt_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['guardian', '-created_at'], name='notificatio_guardia_906ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', '-created_at'], name='notificatio_student_ecaed0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', '-last_attempt_at'], name='notificatio_status_48cb4a_idx'),
        ),
    ]
