# Generated by Django 5.2.17 on 2026-08-30 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('LOW_GRADE', 'Calificación Baja'), ('ABSENCE', 'Falta Individual'), ('REPEATED_ABSENCE', 'Faltas Reiteradas'), ('LATE', 'Atraso')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, default=51.0, max_digits=5, null=True)),
                ('period_days', models.IntegerField(blank=True, default=15, null=True)),
                ('cooldown_hours', models.IntegerField(blank=True, default=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de Notificación',
                'verbose_name_plural': 'Reglas de Notificación',
                'db_table': 'notification_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('GRADE', 'Calificación'), ('ATTENDANCE', 'Asistencia'), ('AGGREGATE', 'Agregado')], max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=200, unique=True)),
                ('severity', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('RESOLVED', 'Resuelto')], default='OPEN', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='academics.student')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='alerts.notificationrule')),
            ],
            options={
                'verbose_name': 'Evento de Alerta',
                'verbose_name_plural': 'Eventos de Alerta',
                'db_table': 'alert_events',
                'ordering': ['-first_detected_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='alert_event_student_03f66a_idx'), models.Index(fields=['rule', 'status'], name='alert_event_rule_id_8d419f_idx')],
            },
        ),
    ]
