# Generated by Django 5.2.17 on 2026-09-04 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(default='BIMONTH', max_length=20)),
                ('number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade_entry_start', models.DateField(blank=True, null=True)),
                ('grade_entry_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planificado'), ('OPEN', 'Abierto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'db_table': 'academic_periods',
                'ordering': ['academic_year', 'number'],
                'unique_together': {('academic_year', 'number')},
            },
        ),
    ]
